apiVersion: v1
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.61.0.9
          port: 22
        public:
          address: 127.0.0.1
          port: 2222
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-1
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.61.0.10
          port: 22
        public:
          address: 127.0.0.1
          port: 2223
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.61.0.11
          port: 22
        public:
          address: 127.0.0.1
          port: 2224
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-1
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.61.0.12
          port: 22
        public:
          address: 127.0.0.1
          port: 2225
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-2
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.61.0.13
          port: 22
        public:
          address: 127.0.0.1
          port: 2226
kind: List
